#!/bin/bash

OPTSTRING="upl:e:h-"

print()
{
  echo "-u, --users - Вывод пользователей и их домашних директорий"
  echo "-p, --processes - Вывод перечня запущенных процессов, отсортированных по идентификатору"
  echo "-h, --help - Вывод справки с перечнем и описанием аргументов и остановка работы"
  echo "-l, --log PATH - Замещение вывода на экран выводом в файл по пути PATH"
  echo "-e, --errors PATH - Замещение вывода ошибок из потока stderr в файл по пути PATH"
}

users()
{
  getent passwd | awk '{print NR,$0}' | sort
}

process()
{
  ps -e -o pid | sort
}

path()
{
  local path="$1"
  if [[! -w "$path"]];
  then
    echo "Нет доступа к файлу $path" >$2
    exit 1
  fi
}

while getopts ${OPTSTRING} opt; do
  case ${opt} in
  u)
      users
      ;;
  p)
      process
      ;;
  l)
      LOGI=${OPTARG}
      path ${LOGI}
      ;;
  e)
      ERRO=${OPTARG}
      path ${ERRO}
      ;;
  h)
      print
      exit 0
      ;;
